"""Event-episode v2 experimental package.

All v2 code is additive and self-contained.  It does NOT modify any module
outside this folder.  Outputs are written under ``outputs/v2/`` and never
overlap with the legacy weekly-questionnaire pipeline.
"""
from __future__ import annotations

from pathlib import Path

from src.config import OUTPUT_ROOT, DATA_PROCESSED, DATA_RAW  # noqa: F401

# v2-only output namespace -- keeps legacy outputs untouched.
OUTPUT_ROOT_V2 = OUTPUT_ROOT / "v2"
OUTPUT_TABLES_V2 = OUTPUT_ROOT_V2 / "tables"
OUTPUT_FIGURES_V2 = OUTPUT_ROOT_V2 / "figures"

# Intermediate parquets (samples, features) live under data/processed/v2 so we
# don't collide with the legacy sensor_features_*.parquet generated by
# scripts/run_questionnaire_event_pipeline.py.
DATA_PROCESSED_V2 = DATA_PROCESSED / "v2"

OUTPUT_TABLES_V2.mkdir(parents=True, exist_ok=True)
OUTPUT_FIGURES_V2.mkdir(parents=True, exist_ok=True)
DATA_PROCESSED_V2.mkdir(parents=True, exist_ok=True)

__all__ = [
    "OUTPUT_ROOT_V2",
    "OUTPUT_TABLES_V2",
    "OUTPUT_FIGURES_V2",
    "DATA_PROCESSED_V2",
]
